"""Alert Manager for NIDS detections.

Provides the primary interface for persisting, querying, updating, and summarizing
security alerts generated by detection modules (Phases 5-9) into SQLite storage.
Adheres to the core principle: "Analyze first, detect second, explain every alert."
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from backend.alert.database import AlertDatabase
from backend.alert.models import Alert, AlertStatus
from backend.config.loader import load_thresholds
from backend.detection.models import DetectionResult

logger = logging.getLogger(__name__)


def serialize_evidence(evidence: Any) -> str:
    """Safely convert evidence structure to a JSON string.

    Converts sets, custom objects, and primitives cleanly without raising TypeErrors.
    """
    if evidence is None:
        return "{}"

    if isinstance(evidence, str):
        # Verify if it's already a valid JSON string
        try:
            json.loads(evidence)
            return evidence
        except Exception:
            return json.dumps({"raw": evidence})

    def _default_encoder(obj: Any) -> Any:
        if isinstance(obj, (set, frozenset)):
            try:
                return sorted(list(obj))
            except TypeError:
                return list(obj)
        if hasattr(obj, "to_dict") and callable(obj.to_dict):
            return obj.to_dict()
        return str(obj)

    try:
        return json.dumps(evidence, default=_default_encoder)
    except Exception as exc:
        logger.warning("Error serializing evidence to JSON: %s", exc)
        return json.dumps({"error": f"Failed to serialize evidence: {exc}"})


def deserialize_evidence(raw_evidence: Optional[str]) -> Dict[str, Any]:
    """Safely deserialize stored JSON evidence into a Python dictionary.

    Guarantees machine-readable output and never raises exceptions on malformed input.
    """
    if not raw_evidence or not isinstance(raw_evidence, str) or not raw_evidence.strip():
        return {}

    try:
        parsed = json.loads(raw_evidence)
        if isinstance(parsed, dict):
            return parsed
        return {"data": parsed}
    except Exception as exc:
        logger.debug("Failed parsing stored evidence JSON: %s. Returning raw envelope.", exc)
        return {"raw": raw_evidence}


def format_timestamp(timestamp: Any) -> str:
    """Format diverse timestamp representations into standard ISO 8601 string."""
    if timestamp is None:
        return datetime.now(timezone.utc).isoformat()

    if isinstance(timestamp, datetime):
        return timestamp.isoformat()

    if isinstance(timestamp, (int, float)):
        try:
            return datetime.fromtimestamp(float(timestamp), tz=timezone.utc).isoformat()
        except (ValueError, OverflowError, OSError):
            return str(timestamp)

    if isinstance(timestamp, str):
        return timestamp.strip()

    return str(timestamp)


class AlertManager:
    """Manages the persistence, querying, status lifecycle, and analytics of detection alerts."""

    def __init__(
        self,
        db_path: Optional[str | Path] = None,
        config_path: Optional[str | Path] = None,
    ) -> None:
        """Initialize AlertManager with SQLite storage.

        If db_path is not explicitly provided, attempts to load it from the database/system
        configuration in thresholds.yaml with fallback to 'nids_events.db'.
        """
        if db_path is not None:
            resolved_path = db_path
        else:
            config = load_thresholds(config_path)
            db_cfg = config.get("database", {})
            sys_cfg = config.get("system", {})
            resolved_path = (
                db_cfg.get("path")
                or sys_cfg.get("db_path")
                or "nids_events.db"
            )

        self.db = AlertDatabase(resolved_path)
        logger.debug("AlertManager initialized with database at '%s'.", self.db.db_path)

    def save_alert(
        self,
        detection_result: DetectionResult | Dict[str, Any],
        status: Optional[str] = None,
    ) -> int:
        """Persist a DetectionResult or alert dictionary into SQLite.

        Validates status, formats timestamps, serializes evidence, and returns the alert ID.
        """
        # Determine target status
        target_status = status
        if target_status is None:
            if isinstance(detection_result, dict) and "status" in detection_result:
                target_status = detection_result["status"]
            else:
                target_status = AlertStatus.NEW

        validated_status = AlertStatus.validate(target_status)

        # Normalize field extraction across DetectionResult dataclass and raw dictionaries
        if isinstance(detection_result, DetectionResult):
            raw_ts = detection_result.timestamp
            alert_type = detection_result.alert_type
            severity = detection_result.severity
            src_ip = detection_result.src_ip
            dst_ip = detection_result.dst_ip
            protocol = detection_result.protocol
            description = detection_result.description
            detection_reason = detection_result.detection_reason
            evidence_data = detection_result.evidence
        elif isinstance(detection_result, dict):
            raw_ts = detection_result.get("timestamp")
            alert_type = detection_result.get("alert_type") or "Security Alert"
            severity = detection_result.get("severity") or "LOW"
            src_ip = detection_result.get("src_ip") or detection_result.get("source_ip")
            dst_ip = detection_result.get("dst_ip") or detection_result.get("destination_ip")
            protocol = detection_result.get("protocol") or "UNKNOWN"
            description = detection_result.get("description") or detection_result.get("detection_reason") or ""
            detection_reason = detection_result.get("detection_reason") or detection_result.get("description") or ""
            evidence_data = detection_result.get("evidence", {})
        else:
            raise TypeError(
                f"Unsupported detection result type: {type(detection_result).__name__}. "
                "Expected DetectionResult or dict."
            )

        ts_str = format_timestamp(raw_ts)
        norm_severity = str(severity).strip().upper()
        evidence_str = serialize_evidence(evidence_data)

        alert_id = self.db.insert_alert(
            timestamp=ts_str,
            alert_type=str(alert_type),
            severity=norm_severity,
            src_ip=str(src_ip) if src_ip is not None else None,
            dst_ip=str(dst_ip) if dst_ip is not None else None,
            protocol=str(protocol).upper() if protocol is not None else None,
            description=str(description) if description is not None else None,
            detection_reason=str(detection_reason) if detection_reason is not None else None,
            evidence=evidence_str,
            status=validated_status,
        )

        logger.debug("Saved alert id=%d type='%s' severity='%s'", alert_id, alert_type, norm_severity)
        return alert_id

    def get_alert(self, alert_id: int) -> Optional[Alert]:
        """Retrieve a single alert by its primary key ID.

        Returns an Alert instance if found, or None if nonexistent.
        """
        row = self.db.get_alert_by_id(alert_id)
        if row is None:
            return None
        return self._row_to_alert(row)

    def get_alerts(
        self,
        limit: Optional[int] = None,
        severity: Optional[str] = None,
        alert_type: Optional[str] = None,
        src_ip: Optional[str] = None,
        status: Optional[str] = None,
        start_time: Optional[str | float] = None,
        end_time: Optional[str | float] = None,
        offset: int = 0,
    ) -> List[Alert]:
        """Retrieve alerts matching optional filters, ordered newest-first by default.

        All filter parameters are bound safely using parameterized SQL.
        """
        clauses: List[str] = []
        params: List[Any] = []

        if severity is not None:
            clauses.append("severity = ?")
            params.append(str(severity).strip().upper())

        if alert_type is not None:
            clauses.append("alert_type = ?")
            params.append(str(alert_type).strip())

        if src_ip is not None:
            clauses.append("src_ip = ?")
            params.append(str(src_ip).strip())

        if status is not None:
            norm_status = AlertStatus.validate(status)
            clauses.append("status = ?")
            params.append(norm_status)

        if start_time is not None:
            start_str = format_timestamp(start_time)
            clauses.append("timestamp >= ?")
            params.append(start_str)

        if end_time is not None:
            end_str = format_timestamp(end_time)
            clauses.append("timestamp <= ?")
            params.append(end_str)

        rows = self.db.query_alerts(
            where_clauses=clauses,
            params=params,
            order_by="timestamp DESC, id DESC",
            limit=limit,
            offset=offset,
        )

        return [self._row_to_alert(r) for r in rows]

    def update_status(self, alert_id: int, new_status: str) -> bool:
        """Update lifecycle status of an alert (NEW, ACKNOWLEDGED, RESOLVED).

        Rejects invalid statuses safely with ValueError.
        Returns True if the alert was updated, False if alert_id does not exist.
        """
        validated = AlertStatus.validate(new_status)
        return self.db.update_alert_status(alert_id, validated)

    def get_recent_alerts(self, limit: int = 10) -> List[Alert]:
        """Convenience method returning the N most recent alerts."""
        return self.get_alerts(limit=limit)

    def get_alert_count(
        self,
        status: Optional[str] = None,
        severity: Optional[str] = None,
    ) -> int:
        """Return total count of alerts matching optional status and severity filters."""
        clauses: List[str] = []
        params: List[Any] = []

        if status is not None:
            clauses.append("status = ?")
            params.append(AlertStatus.validate(status))

        if severity is not None:
            clauses.append("severity = ?")
            params.append(str(severity).strip().upper())

        return self.db.count_alerts(where_clauses=clauses, params=params)

    def get_severity_counts(self) -> Dict[str, int]:
        """Return aggregated dictionary of alert counts mapped by severity."""
        return self.db.get_grouped_counts("severity")

    def get_alert_type_counts(self) -> Dict[str, int]:
        """Return aggregated dictionary of alert counts mapped by alert type."""
        return self.db.get_grouped_counts("alert_type")

    def get_status_counts(self) -> Dict[str, int]:
        """Return aggregated dictionary of alert counts mapped by lifecycle status."""
        return self.db.get_grouped_counts("status")

    def delete_alert(self, alert_id: int) -> bool:
        """Delete an alert by ID. Returns True if deleted, False otherwise."""
        return self.db.delete_alert(alert_id)

    def clear_all_alerts(self) -> int:
        """Delete all alerts from the database. Returns count of deleted rows."""
        return self.db.clear_alerts()

    @staticmethod
    def _row_to_alert(row: Any) -> Alert:
        """Convert a SQLite row into a strongly-typed Alert object."""
        return Alert(
            id=int(row["id"]),
            timestamp=str(row["timestamp"]),
            alert_type=str(row["alert_type"]),
            severity=str(row["severity"]),
            src_ip=str(row["src_ip"]) if row["src_ip"] is not None else None,
            dst_ip=str(row["dst_ip"]) if row["dst_ip"] is not None else None,
            protocol=str(row["protocol"]) if row["protocol"] is not None else None,
            description=str(row["description"]) if row["description"] is not None else None,
            detection_reason=str(row["detection_reason"]) if row["detection_reason"] is not None else None,
            evidence=deserialize_evidence(row["evidence"]),
            status=str(row["status"]),
        )
