"""Detection data models for the NIDS rule engines.

Defines standardized, explainable `DetectionResult` structures generated by
detection modules and consumed by the Alert Manager.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class DetectionResult:
    """Represents the explainable outcome of a security detection rule evaluation.

    Adheres to the core principle: "Analyze first, detect second, explain every alert."
    """

    rule_name: str
    alert_type: str
    severity: str
    src_ip: str
    dst_ip: Optional[str] = None
    protocol: str = "TCP"
    scan_type: Optional[str] = None  # e.g., "VERTICAL", "HORIZONTAL", "SYN_SCAN", "SYN_RATE_ANOMALY"
    detection_type: Optional[str] = None
    incomplete_ratio: Optional[float] = None

    timestamp: float = field(default_factory=time.time)
    window_seconds: float = 1.0
    start_time: float = 0.0
    end_time: float = 0.0

    syn_count: int = 0
    unique_destination_ports: int = 0
    unique_destination_ips: int = 0

    detected: bool = True
    threshold_values: Dict[str, Any] = field(default_factory=dict)
    detection_reason: str = ""
    evidence: Dict[str, Any] = field(default_factory=dict)
    dst_port: Optional[int] = None

    def __post_init__(self) -> None:
        """Synchronize detection_type and scan_type aliases."""
        if self.detection_type is None and self.scan_type is not None:
            object.__setattr__(self, "detection_type", self.scan_type)
        elif self.scan_type is None and self.detection_type is not None:
            object.__setattr__(self, "scan_type", self.detection_type)

    @property
    def source_ip(self) -> str:
        """Alias for src_ip."""
        return self.src_ip

    @property
    def destination_ip(self) -> Optional[str]:
        """Alias for dst_ip."""
        return self.dst_ip

    @property
    def destination_port(self) -> Optional[int]:
        """Alias for dst_port."""
        return self.dst_port

    @property
    def reason(self) -> str:
        """Alias for detection_reason."""
        return self.detection_reason

    @property
    def observed_syn_count(self) -> int:
        """Alias for syn_count."""
        return self.syn_count

    @property
    def configured_ratio_threshold(self) -> Optional[float]:
        """Convenience accessor for configured incomplete ratio threshold."""
        return self.threshold_values.get("incomplete_ratio_threshold")

    def to_dict(self) -> Dict[str, Any]:
        """Serialize detection result to dictionary."""
        return {
            "detected": self.detected,
            "rule_name": self.rule_name,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "src_ip": self.src_ip,
            "dst_ip": self.dst_ip,
            "dst_port": self.dst_port,
            "protocol": self.protocol,
            "scan_type": self.scan_type,
            "detection_type": self.detection_type or self.scan_type,
            "incomplete_ratio": self.incomplete_ratio,
            "timestamp": self.timestamp,
            "window_seconds": self.window_seconds,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "syn_count": self.syn_count,
            "unique_destination_ports": self.unique_destination_ports,
            "unique_destination_ips": self.unique_destination_ips,
            "threshold_values": dict(self.threshold_values),
            "detection_reason": self.detection_reason,
            "evidence": dict(self.evidence),
        }

    def __str__(self) -> str:
        target = f" -> {self.dst_ip}" if self.dst_ip else ""
        return (
            f"[{self.severity}] {self.alert_type} ({self.scan_type or self.rule_name}): "
            f"{self.src_ip}{target} | {self.detection_reason}"
        )
